# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Guilherme Teixeira"
email: 'guiemi.teixeira@gmail.com'
description: "Web Developer • Linguistics Undergraduate Student"


quick_bio: "Hello, my name is Guilherme Teixeira. I'm a beginner-level developer, and a linguistics undergraduate student based in São Paulo, Brazil. I love computers, inline-skating, and I love to read about linguistics and science in general, science fiction, and fantasy literature. I also enjoy watching NBA on TV in the spare time.

I'm currently learning Python (and Django) and JavaScript (and Vue.js) too. I'm also studying NLP (Natural Language Processing) in the college. I hope to know a bit more about Machine Learning and Formal Syntax as well in the near future."

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guiemi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 'guiemiquestion'
github_username: 'guiemi'
medium_username: 'guiemi'
linkedin_username: 'guiemi'
quora_username: 'Guilherme-Teixeira'
lastfm_username: 'guirgo'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 5
footer_text: 'Jami Gibbs'
admin_name: 'Guilherme Teixeira'
google_analytics: "UA-139424409-1" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: false
nav_item:
  - { url: '/', text: 'Página Inicial' }
  - { url: '/about', text: 'Sobre' }
