title: "Guilherme Teixeira"
email: 'guiemi.teixeira@gmail.com'
# description: Computational Linguistics Intern • Developer • Undergraduate Linguistics Student 
description: Developer && Linguistics Student 

quick_bio: ""

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guiemi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 'vibraniumdev'
github_username: 'guiemi'
medium_username: 'blacktech'
linkedin_username: 'guiemi'
# quora_username: 'Guilherme-Teixeira'
lastfm_username: 'guirgo'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate
  - jekyll-get-json

### Phantom settings
paginate: 5
footer_text: 'Jami Gibbs'
admin_name: 'Guilherme Teixeira'
google_analytics: "UA-139424409-1" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  # - { url: '/', text: 'Página Inicial' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/about', text: 'About' }

#### Jekyll Get Json
jekyll_get_json:
  - data: repos
    json: curl https://api.github.com/users/guiemi/repos
    
    # json: curl https://api.github.com/users/guiemi/repos
    # json: "9d71a8c4106f4ea74ef9:f9ff9a14fad8c26a809624c6bd2007690311b4af https://api.github.com/guiemi/repos"  # Pattern 1 | didn't work
    # json: 9d71a8c4106f4ea74ef9:f9ff9a14fad8c26a809624c6bd2007690311b4af "https://api.github.com/guiemi/repos"  # Pattern 2 | didn't work
    # json: curl -u 9d71a8c4106f4ea74ef9:f9ff9a14fad8c26a809624c6bd2007690311b4af https://api.github.com/guiemi/repos  # Pattern 3 | didn't work
    # json: curl -u "9d71a8c4106f4ea74ef9:f9ff9a14fad8c26a809624c6bd2007690311b4af https://api.github.com/guiemi/repos"  # Pattern 4 | didn't work
    # json: 'https://api.github.com/users/guiemi/repos'  # Deprecated? | works!
